packages:
  device: !include device.yaml # include our test device setup

external_components:
  - source:
      type: local
      path: components

# Enable logging
logger:
  level: VERBOSE

sensor:
  - platform: vl53l1x_sensor
    name: Default sensor
  - platform: vl53l1x_sensor
    name: Basic settings
    timing_budget: 20ms
    distance_mode: LONG
  - platform: vl53l1x_sensor
    name: Full config
    enable_pin: GPIO10
    distance_mode: MEDIUM
    timing_budget: 200ms
    signal_threshold: 512
    update_interval: 1s
    address: 0x32
    accuracy_decimals: 2
    ambient_rate_sensor:
      name: "ambient_rate"
    avg_signal_rate_sensor:
      name: "avg_signal_rate"
    peak_signal_rate_sensor:
      name: "peak_signal_rate"
    range_status_sensor:
      name: "range_status"
    roi_center: 199
    roi_size:
      x: 4
      y: 4
  - platform: vl53l1x_sensor
    name: ROI settings
    roi_center:
      x: 3
      y: 8
    roi_size:
      x: 4
      y: 4
  - platform: vl53l1x_sensor
    id: calibrated_sensor
    name: Calibrated sensor
    calibration:
      offset: 15
      xtalk: 300

button:
  - platform: template
    name: "Calibrate"
    on_press:
      - vl53l1x_sensor.calibrate:
          id: calibrated_sensor
          offset_cal_distance: 140  # mm, 17% gray target distance for offset
          xtalk_cal_distance: 600   # mm, max ranging distance with cover glass for xtalk
  - platform: template
    name: "Calibrate Offset Only"
    on_press:
      - vl53l1x_sensor.calibrate_offset:
          id: calibrated_sensor
          value: 140
  - platform: template
    name: "Calibrate Xtalk Only"
    on_press:
      - vl53l1x_sensor.calibrate_xtalk:
          id: calibrated_sensor
          value: 600

i2c:
  sda: 4
  scl: 5
